// <auto-generated />
using System;
using Ecommerce.DataAccess.ConnexionDB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Ecommerce.DataAccess.Migrations
{
    [DbContext(typeof(EcommerceContext))]
    [Migration("20220204220657_Ecommerce11")]
    partial class Ecommerce11
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Ecommerce")
                .HasAnnotation("EcommerceVersion", "1.1")
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Ecommerce.DataAccess.Model.Category", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("Photo");

                    b.HasKey("ID");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("Ecommerce.DataAccess.Model.Product", b =>
                {
                    b.Property<int>("ID");

                    b.Property<decimal>("CurrentPrice")
                        .HasColumnType("decimal(6, 2)");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<bool?>("Is_Available")
                        .ValueGeneratedOnAdd();

                    b.Property<bool?>("Is_Promotion")
                        .ValueGeneratedOnAdd();

                    b.Property<bool?>("Is_Selected")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Name")
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.Property<string>("PhotoName");

                    b.Property<int>("Quantity");

                    b.HasKey("ID");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("Ecommerce.DataAccess.Model.Product", b =>
                {
                    b.HasOne("Ecommerce.DataAccess.Model.Category", "Category_")
                        .WithMany("Product_")
                        .HasForeignKey("ID")
                        .HasConstraintName("FK_Product_Category")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
